export const images = {
  logo: "/kelalmenu_logo.jpg",
  about_side: "/about_side.png",
  loading_gif: "/loading.gif",
  logo_url:
    "https://ik.imagekit.io/kelalmenu/kelalmenu_logo.jpg?updatedAt=1760080318134",
  food_image:
    "https://ik.imagekit.io/kelalmenu/istockphoto-1457433817-612x612.jpg?updatedAt=1761298853448",
};

export const links = {
  home: "/",
  base_url: "https://www.kelalmenu.com",
  about: "/#about",
  pricing: "/pricing",
  contact_us: "/#contact_us",
  login: "/auth/login",
  register: "/auth/register",
  hotel_dashboard: "/kelalmenu/hotels/dashboard",
  public_menu: "public-menu",
};

export const hotel_links = [
  {
    label: "Profile",
    isActive: true,
    link: "profile",
    desc: "update your hotel information",
  },
  {
    label: "Menu",
    isActive: true,
    link: "menu",
    desc: "update and add new Menu item",
  },
  {
    label: "My QR Code",
    isActive: true,
    link: "my-qr-code",
    desc: "Generate -> Print your QR code",
  },
  {
    label: "My Ad Campaigns",
    isActive: true,
    link: "my-ad-campaigns",
    desc: "Create -> update your Ad",
  },
  {
    label: "Upgrade",
    isActive: true,
    link: "upgrade",
    desc: "Upgrade your subscription level",
  },
  {
    label: "Orders",
    isActive: false,
    link: "orders",
    desc: "Check and see your orders",
  },
  {
    label: "Analytics",
    isActive: false,
    link: "analytics",
    desc: "see your menu analytics",
  },
  {
    label: "Settings",
    isActive: false,
    link: "settings",
    desc: "update your setting",
  },
];
export const constants = {
  name: "kelalmenu",
  syllable: ": Transform Your Restaurant Menu into a Digital QR Code",
};

export const errors = {
  somethingWentWrong: {
    error: true,
    success: false,
    data: null,
    message: "Something went wrong please try again",
  },
};

export const success = {
  error: false,
  success: true,
  data: null,
  message: "Operation successful",
};

export const metadataKeywordsList = {
  geographic: [
    "Ethiopia digital menu",
    "Addis Ababa QR code menu",
    "Ethiopian restaurant app",
    "Africa contactless menu",
    "East Africa menu digitization",
  ],
  foodBased: [
    "Ethiopian cuisine QR menu",
    "Injera digital ordering",
    "Tibs restaurant menu app",
    "Kitfo contactless menu",
    "Doro wat online menu",
    "Coffee ceremony digital menu",
    "Shiro food QR code",
    "Ethiopian injera app",
  ],
  general: [
    "digital menu",
    "QR code menu",
    "restaurant menu app",
    "contactless menu",
    "menu digitization",
    "online menu system",
    "mobile restaurant menu",
    "real-time menu updates",
    "QR ordering system",
    "restaurant tech solution",
  ],
};

const metadataKeywords = [
  ...metadataKeywordsList.geographic,
  ...metadataKeywordsList.foodBased,
  ...metadataKeywordsList.general,
].join(", ");

export const basic_metadata = {
  title: `${constants.name} ${constants.syllable}`,
  description: `Revolutionize your dining experience with ${constants.name}. Easily convert traditional menus to interactive digital QR code menus. Boost efficiency, reduce printing costs, and engage customers with real-time updates. Start free today!`,
  keywords: metadataKeywords,
  metadataBase: new URL(`${links.base_url}`),
  openGraph: {
    title: `${constants.name} ${constants.syllable}`,
    description: `Revolutionize your dining experience with ${constants.name}. Easily convert traditional menus to interactive digital QR code menus. Boost efficiency, reduce printing costs, and engage customers with real-time updates. Start free today!`,
    url: `${constants.name}`,
    siteName: constants.name,
    images: [
      {
        url: "/opengraph-image.jpg",
        width: 1200,
        height: 630,
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: `${constants.name} ${constants.syllable}`,
    description: `Revolutionize your dining experience with ${constants.name}. Easily convert traditional menus to interactive digital QR code menus. Boost efficiency, reduce printing costs, and engage customers with real-time updates. Start free today!`,
    images: ["/twitter-image.jpg"],
  },
};

export const navLinks = [
  {
    url: links.home,
    label: "Home",
    isActive: true,
  },
  {
    url: links.about,
    label: "About",
    isActive: true,
  },
  {
    url: links.contact_us,
    label: "Contact us",
    isActive: true,
  },
  {
    url: links.pricing,
    label: "Pricing",
    isActive: true,
  },
];

export const basic_info = {
  email: "contact@agelgl.com",
  phoneCTA: "tel: +251919298886",
  phone: "+251919298886",
};

export const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands (the)",
  "Central African Republic (the)",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];

export const categories = [
  { label: "Breakfast", plan: "all" },
  { label: "Lunch", plan: "all" },
  { label: "Dinner", plan: "all" },
  { label: "Snack", plan: "paid" },
  { label: "Desserts", plan: "paid" },
  { label: "Lunch / Dinner", plan: "paid" },
  { label: "Juice / Drinks", plan: "paid" },
  { label: "Hot Beverages", plan: "paid" },
  { label: "Cold Beverages", plan: "paid" },
  { label: "Alcohol Drinks", plan: "paid" },
  { label: "All Day", plan: "paid" },
];

export const subCategoryOptions = [
  {
    group: "Ethiopian 🇪🇹",
    items: ["Injera", "Shiro", "Doro Wat", "Tibs", "Firfir", "Kitfo"],
  },
  {
    group: "Indian 🇮🇳",
    items: [
      "Biryani",
      "Samosa",
      "Paneer Butter Masala",
      "Naan",
      "Masala Dosa",
      "Chaat",
    ],
  },
  {
    group: "Italian 🇮🇹",
    items: ["Pizza", "Pasta", "Lasagna", "Risotto", "Bruschetta"],
  },
  {
    group: "American 🇺🇸",
    items: ["Burger", "Hotdog", "Fried Chicken", "Steak", "Pancakes"],
  },
  {
    group: "Asian 🍜",
    items: ["Sushi", "Ramen", "Dim Sum", "Pad Thai", "Spring Rolls"],
  },
  {
    group: "Middle Eastern 🌍",
    items: ["Shawarma", "Falafel", "Hummus", "Kebab", "Tabbouleh"],
  },
  {
    group: "African 🌍",
    items: ["Jollof Rice", "Ugali", "Bobotie", "Pilau", "Suya"],
  },
  {
    group: "Latin American 🇲🇽",
    items: ["Tacos", "Burrito", "Empanada", "Arepa", "Churros"],
  },
  {
    group: "European 🇪🇺",
    items: ["Croissant", "Paella", "Schnitzel", "Crepe", "Goulash"],
  },
  {
    group: "Drinks & Juice 🍹",
    items: ["Coffee", "Tea", "Smoothie", "Juice", "Milkshake", "Cocktail"],
  },
];

export const planLimits = {
  free: { categories: 3, subcategories: 5, itemsPerSubcategory: 5, total: 25 },
  standard: {
    categories: Infinity,
    subcategories: 20,
    itemsPerSubcategory: Infinity,
    total: Infinity,
  },
  premium: {
    categories: Infinity,
    subcategories: 40,
    itemsPerSubcategory: Infinity,
    total: Infinity,
  },
  enterprise: {
    categories: Infinity,
    subcategories: Infinity,
    itemsPerSubcategory: Infinity,
    total: Infinity,
  },
};
